- ${jobNum}_${projectName}:
  - ${jobNum}-${partNum}_${projectName}_CommonFiles:
    - ORIGINALS-SOURCE:
      - FROM CLIENT:
      - FROM ITK:
    - WORKING-FILES:
      - LINKS:
        - LOGOS:
        - RASTER:
          - FINAL:
          - WORKING:
        - VECTOR:
          - FINAL:
          - WORKING:
      - NATIVE FILES:
        - ACROBAT:
        - AFTER EFFECTS:
          - BACKUP:
        - CODE:
          - VISUAL-STUDIO:
        - ILLUSTRATOR:
          - BACKUP:
        - FRESCO:
          - BACKUP:
        - PHOTOSHOP:
          - BACKUP:
        - COMFY:
          - BACKUP:
        - EXSTAR:
          - BACKUP:
        - BLENDER:
          - BACKUP:
      - SUPPORT:
    - _OUTPUT:
      - 01-FINAL:
      - 02-REVIEW:
      - 03-DELIVERY-PACKAGES:
      - 04-SUPPORT:
  - ${jobNum}-${partNum}_${projectName}_${partName}:
    - ORIGINALS-SOURCE:
    - WORKING-FILES:
      - LINKS:
        - LOGOS:
        - RASTER:
          - FINAL:
          - WORKING:
        - VECTOR:
          - FINAL:
          - WORKING:
      - NATIVE FILES:
        - ACROBAT:
        - AFTER EFFECTS:
          - BACKUP:
        - CODE:
          - VISUAL-STUDIO:
        - ILLUSTRATOR:
          - BACKUP:
        - FRESCO:
          - BACKUP:
        - PHOTOSHOP:
          - BACKUP:
        - COMFY:
          - BACKUP:
        - EXSTAR:
          - BACKUP:
        - BLENDER:
          - BACKUP:
      - SUPPORT:
        - BACKUPS:
    - _OUTPUT:
      - 01-FINAL:
      - 02-REVIEW:
      - 03-DELIVERY-PACKAGES:
      - 04-SUPPORT:
